package com.sample

import com.sample.DroolsTest.Init; 
import com.sample.DroolsTest.Jaki_budzet;
import com.sample.DroolsTest.Czy_terenowy;
import com.sample.DroolsTest.Czy_mercedes;
import com.sample.DroolsTest.Samochod_rodzinny;
import com.sample.DroolsTest.Pojemny_bagaznik;
import com.sample.DroolsTest.Samochod_sportowy;
import com.sample.DroolsTest.Samochod_miejski;
import com.sample.DroolsTest.Samochod_cabrio;
import com.sample.DroolsTest.Samochod_combi;
import com.sample.DroolsTest.Samochod_coupe;
import com.sample.DroolsTest.Limuzyna;
import com.sample.DroolsTest.Van;
import javax.swing.JOptionPane;

rule "init"
	when
	then
		insert(new Init());
end


rule "Jaki budzet"
	when
		x:Init()
	then		
		JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.budzet, "Pytanie", JOptionPane.YES_NO_OPTION, 
			JOptionPane.QUESTION_MESSAGE, null, x.rodzaj_budzetu, x.rodzaj_budzetu[0]); 
		insert(new Jaki_budzet(n+1));
end

rule "Czy terenowy"
	when
		x:Init()
		exists(Jaki_budzet(w == 1 || w == 2 || w == 3));
	then
		JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.terenowy, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
		insert(new Czy_terenowy(n));
end 


rule "Czy mercedes"
	when 
		x:Init()
		exists Czy_terenowy(w == 1);
		exists Jaki_budzet(w == 1 || w == 2 || w == 3 )
	then	
		JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.mercedes, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
    	insert(new Czy_mercedes(n));
end
		
rule "Samochod rodzinny"
	when
		x:Init() 
		exists Czy_terenowy(w == 0);
	then
	 	JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.rodzinny, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
    	insert(new Samochod_rodzinny(n));
end		

rule "Pojemny bagaznik"
	when 
		x:Init()
		exists Samochod_rodzinny(w == 1);
	then
    	JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.pojemny, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
	 	insert(new Pojemny_bagaznik(n));
end

rule "Samochod sportowy"
	when 
		x:Init()
		exists Samochod_rodzinny(w == 0);
	then
   		JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.sportowy, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
   		insert(new Samochod_sportowy(n));
end
	
rule "Samochod miejski"
	when 
		x:Init()
		exists Samochod_sportowy(w == 0);
	then
	 	JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.miejski, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
    	insert(new Samochod_miejski(n));
end		

rule "Samochod cabrio"
	when 
		x:Init()
		exists Samochod_sportowy(w == 1);
	then
	 	JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.cabrio, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
    	insert(new Samochod_cabrio(n));
end		

rule "Samochod combi"
	when 
		x:Init()
		exists Samochod_miejski(w == 0);
	then
   		JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.combi, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
		insert(new Samochod_combi(n));
end	

rule "Samochod coupe"
	when 
		x:Init()
		exists Samochod_combi(w == 0);
	then
	 	JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.coupe, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
   		insert(new Samochod_coupe(n));
end		

rule "Limuzyna"
	when 
		x:Init()
		exists Samochod_coupe(w == 0);
	then	
		JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.limuzyna, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
		insert(new Limuzyna(n));
end		

rule "Van"
	when 
		x:Init()
		exists Limuzyna(w == 0);
	then	
		JOptionPane frame = new JOptionPane();
		int n = JOptionPane.showOptionDialog(frame, x.van, "Pytanie", JOptionPane.YES_NO_OPTION,
	   		 JOptionPane.QUESTION_MESSAGE, null, x.tab, x.tab[0]); 
		insert(new Van(n));
end		
	
		
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////	
				
rule "Brak propozycji"
 	when
 		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==1);
 		exists Czy_mercedes(w==1);
 	then
 		System.out.println("Brak propozycji w wybranym budzecie");
 		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Brak propozycji w wybranym budzecie");
end

rule "Mercedes GLK Off-roader"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==1);
 		exists Czy_mercedes(w==1);
 	then
 		System.out.println("Mercedes GLK Off-roader");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Mercedes GLK Off-roader");
end	

rule "Mercedes G65 AMG"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==1);
 		exists Czy_mercedes(w==1);
 	then
 		System.out.println("Mercedes G65 AMG");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Mercedes G65 AMG");
end

rule "Skoda Yeti"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Czy_mercedes(w==0);
 	then
 		System.out.println("Skoda Yeti");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Skoda Yeti");
end

rule "Volkswagen Touareg"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Czy_mercedes(w==0);
 	then
 		System.out.println("Volkswagen Touareg");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Volskwagen Touareg");
end	

rule "BMW X6"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Czy_mercedes(w==0);
 	then
 		System.out.println("BMW X6");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie BMW X6");
end

rule "Pegueot 5008"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==1);
 		exists Pojemny_bagaznik(w==1);
 	then
 		System.out.println("Pegueot 5008");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Pegueot 5008");
end

rule "Volvo V70"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==1);
 		exists Pojemny_bagaznik(w==1);
 	then
 		System.out.println("Volvo V70");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Volvo V70");
end

rule "Mercedes M"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==1);
 		exists Pojemny_bagaznik(w==1);
 	then
 		System.out.println("Mercedes M");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Mercedes M");
end

rule "Renault Kangoo"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==1);
 		exists Pojemny_bagaznik(w==0);
 	then
 		System.out.println("Renault Kangoo");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Renault Kangoo");
end

rule "Volkswagen Sharan"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==1);
 		exists Pojemny_bagaznik(w==0);
 	then
 		System.out.println("Volskwagen Sharan");
 		JOptionPane frame = new JOptionPane();
 		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Volkswagen Sharan");
end

rule "Volvo S80"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==1);
 		exists Pojemny_bagaznik(w==0);
	then 
		System.out.println("Volvo S80");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Volvo S80");
end

rule "Renault Megane R.S 265"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==1);
 		exists Samochod_cabrio(w==0);
	then 
		System.out.println("Renault Megane R.S 265");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Renault Megane R.S 265");
end

rule "Audi TT"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==1);
 		exists Samochod_cabrio(w==0);
	then 
		System.out.println("Audi TT");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Audi TT");
end

rule "Lamborghini Aventador"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==1);
 		exists Samochod_cabrio(w==0);
	then 
		System.out.println("Lamborghini Aventador");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Lamborghini Aventador");
end

rule "Volkswagen Golf Cabriolet"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==1);
 		exists Samochod_cabrio(w==1);
	then 
		System.out.println("Volkswagen Golf Cabriolet");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Volkswagen Golf Cabriolet");
end

rule "BMW serii 2 Cabrio"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==1);
 		exists Samochod_cabrio(w==1);
	then 
		System.out.println("BMW serii 2 Cabrio");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie BMW serii 2 Cabrio");
end

rule "Ferrari Italia Cabrio"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==1);
 		exists Samochod_cabrio(w==1);
	then 
		System.out.println("Ferrari Italia Cabrio");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Ferrari Italia Cabrio");
end

rule "Skoda Citigo"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==1);
	then 
		System.out.println("Skoda Citigo");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Skoda Citigo");
end

rule "Smart"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==1);
	then 
		System.out.println("Smart");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Smart");
end

rule "Mini John Cooper"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==1);
	then 
		System.out.println("Mini John Cooper");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Mini John Cooper");
end

rule "Skoda Octavia Combi"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==1)
	then 
		System.out.println("Skoda Octavia Combi");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Skoda Octavia Combi");
end

rule "Audi A6 Combi"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==1)
	then 
		System.out.println("Audi A6 Combi");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Audi A6 Combi");
end

rule "Mercedes E Combi"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==1)
	then 
		System.out.println("Mercedes E Combi");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Mercedes E Combi");
end


rule "Toyota Auris Coupe"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==1);
	then 
		System.out.println("Toyota Auris Coupe");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Toyota Auris Coupe");
end

rule "Volkswagen Sirocco"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==1);
	then 
		System.out.println("Volkswagen Sirocco");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Volkswagen Sirocco");
end

rule "BMW serii 6 coupe"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==1);
	then 
		System.out.println("BMW serii 6 coupe");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie BMW serii 6 coupe");
end

rule "Skoda Octavia"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==1);
	then 
		System.out.println("Skoda Octavia");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Skoda Octavia");
end

rule "Mercedes klasa C"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==1);
	then 
		System.out.println("Mercedes klasa C");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Mercedes klasa C");
end

rule "Audi A8"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==1);
	then 
		System.out.println("Audi A8");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Audi A8");
end

rule "Renault Trafic"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==0);
 		exists Van(w==1);
	then 
		System.out.println("Renault Trafic");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Renault Trafic");
end

rule "Volkswagen Transporter"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==0);
 		exists Van(w==1);
	then 
		System.out.println("Volkswagen Transporter");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Volkswagen Transporter");
end

rule "Mercedes klasa V"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==0);
 		exists Van(w==1);
	then 
		System.out.println("Mercedes klasa V");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Mercedes klasa V");
end

rule "Pegout 301 Sedan"
	when
		exists Jaki_budzet(w==1);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==0);
 		exists Van(w==0);
	then 
		System.out.println("Pegout 301 Sedan");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Pegout 301 Sedan");
end

rule "Honda Accord"
	when
		exists Jaki_budzet(w==2);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==0);
 		exists Van(w==0);
	then 
		System.out.println("Honda Accord");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Honda Accord");
end

rule "Audi A7"
	when
		exists Jaki_budzet(w==3);
 		exists Czy_terenowy(w==0);
 		exists Samochod_rodzinny(w==0);
 		exists Samochod_sportowy(w==0);
 		exists Samochod_miejski(w==0);
 		exists Samochod_combi(w==0);
 		exists Samochod_coupe(w==0);
 		exists Limuzyna(w==0);
 		exists Van(w==0);
	then 
		System.out.println("Audi A7");
		JOptionPane frame = new JOptionPane();
		JOptionPane.showMessageDialog(frame, "Najlepszym wyborem bêdzie Audi A7");
end

